/****** Objeto: Schema [G3] Fecha de script: 20/07/2026 19:35:38 ******/
CREATE SCHEMA [G3]
GO
/****** Objeto: Table [G3].[CALENDARIO] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[CALENDARIO](
	[Date] [date] NOT NULL,
	[anio] [int] NOT NULL,
	[mes] [int] NOT NULL,
	[anio_mes] [nvarchar](10) NOT NULL,
	[dia] [int] NOT NULL,
	[mes_nombre] [nvarchar](20) NOT NULL,
	[dia_semana_nombre] [nvarchar](20) NOT NULL,
	[trimestre] [int] NOT NULL,
	[offset_mes_actual] [int] NOT NULL,
 CONSTRAINT [PK_CALENDARIO] PRIMARY KEY CLUSTERED 
(
	[Date] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[CAMPANA] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[CAMPANA](
	[campana_id] [int] NOT NULL,
	[nombre_campana] [nvarchar](50) NOT NULL,
	[fecha_inicio] [date] NOT NULL,
	[fecha_fin] [date] NOT NULL,
 CONSTRAINT [PK_CAMPANA] PRIMARY KEY CLUSTERED 
(
	[campana_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[CLIMA] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[CLIMA](
	[clima_id] [int] NOT NULL,
	[fecha] [date] NOT NULL,
	[temperatura_max] [decimal](5, 1) NOT NULL,
	[temperatura_min] [decimal](5, 1) NOT NULL,
	[humedad_relativa] [decimal](5, 1) NOT NULL,
	[precipitacion_mm] [decimal](5, 1) NOT NULL,
	[condicion] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CLIMA] PRIMARY KEY CLUSTERED 
(
	[clima_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_CLIMA_FECHA] UNIQUE NONCLUSTERED 
(
	[fecha] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[LINEA_EMPAQUE] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[LINEA_EMPAQUE](
	[linea_empaque_id] [int] NOT NULL,
	[nombre_linea] [nvarchar](50) NOT NULL,
	[planta_id] [int] NOT NULL,
 CONSTRAINT [PK_LINEA_EMPAQUE] PRIMARY KEY CLUSTERED 
(
	[linea_empaque_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[LOTE] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[LOTE](
	[lote_id] [int] NOT NULL,
	[produccion_id] [int] NOT NULL,
	[mercado_id] [int] NOT NULL,
	[region_id] [int] NOT NULL,
	[linea_empaque_id] [int] NOT NULL,
	[fecha_empaque] [date] NOT NULL,
 CONSTRAINT [PK_LOTE] PRIMARY KEY CLUSTERED 
(
	[lote_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[MERCADO] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[MERCADO](
	[mercado_id] [int] NOT NULL,
	[tipo_mercado] [nvarchar](50) NOT NULL,
	[precio_por_kg] [int] NOT NULL,
 CONSTRAINT [PK_MERCADO] PRIMARY KEY CLUSTERED 
(
	[mercado_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[METRICA] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[METRICA](
	[metrica_id] [int] NOT NULL,
	[nombre_metrica] [nvarchar](50) NOT NULL,
	[valor_minimo] [int] NOT NULL,
	[unidad_medida] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_METRICA] PRIMARY KEY CLUSTERED 
(
	[metrica_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[METRICA_KILOGRAMO] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[METRICA_KILOGRAMO](
	[metrica_kilogramo_id] [int] NOT NULL,
	[lote_id] [int] NOT NULL,
	[metrica_id] [int] NOT NULL,
	[valor_medido] [decimal](10, 2) NOT NULL,
	[calificacion] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_METRICA_KILOGRAMO] PRIMARY KEY CLUSTERED 
(
	[metrica_kilogramo_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[PLANTA] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[PLANTA](
	[planta_id] [int] NOT NULL,
	[nombre_planta] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_PLANTA] PRIMARY KEY CLUSTERED 
(
	[planta_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[PRODUCCION] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[PRODUCCION](
	[produccion_id] [int] NOT NULL,
	[campana_id] [int] NOT NULL,
	[variedad_id] [int] NOT NULL,
	[fecha_poda] [date] NOT NULL,
	[fecha_brotamiento] [date] NOT NULL,
	[fecha_fructificacion] [date] NOT NULL,
	[fecha_cosecha] [date] NOT NULL,
 CONSTRAINT [PK_PRODUCCION] PRIMARY KEY CLUSTERED 
(
	[produccion_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[PRODUCCION_FECHAS] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[PRODUCCION_FECHAS](
	[produccion_fecha_id] [int] NOT NULL,
	[produccion_id] [int] NOT NULL,
	[fecha] [date] NOT NULL,
	[etapa] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_PRODUCCION_FECHAS] PRIMARY KEY CLUSTERED 
(
	[produccion_fecha_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[REGION] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[REGION](
	[region_id] [int] NOT NULL,
	[nombre_region] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_REGION] PRIMARY KEY CLUSTERED 
(
	[region_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[TRABAJADOR] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[TRABAJADOR](
	[trabajador_id] [int] NOT NULL,
	[nombre_trabajador] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_TRABAJADOR] PRIMARY KEY CLUSTERED 
(
	[trabajador_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[TRABAJADOR_LINEA] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[TRABAJADOR_LINEA](
	[trabajador_linea_id] [int] NOT NULL,
	[linea_empaque_id] [int] NOT NULL,
	[trabajador_id] [int] NOT NULL,
	[supervisor] [bit] NOT NULL,
	[fecha_inicio] [date] NOT NULL,
	[fecha_fin] [date] NOT NULL,
 CONSTRAINT [PK_TRABAJADOR_LINEA] PRIMARY KEY CLUSTERED 
(
	[trabajador_linea_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [G3].[VARIEDAD] Fecha de script: 20/07/2026 19:35:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [G3].[VARIEDAD](
	[variedad_id] [int] NOT NULL,
	[nombre_variedad] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_VARIEDAD] PRIMARY KEY CLUSTERED 
(
	[variedad_id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [G3].[LINEA_EMPAQUE]  WITH CHECK ADD  CONSTRAINT [FK_LINEA_PLANTA] FOREIGN KEY([planta_id])
REFERENCES [G3].[PLANTA] ([planta_id])
GO
ALTER TABLE [G3].[LINEA_EMPAQUE] CHECK CONSTRAINT [FK_LINEA_PLANTA]
GO
ALTER TABLE [G3].[LOTE]  WITH CHECK ADD  CONSTRAINT [FK_LOTE_CALENDARIO] FOREIGN KEY([fecha_empaque])
REFERENCES [G3].[CALENDARIO] ([Date])
GO
ALTER TABLE [G3].[LOTE] CHECK CONSTRAINT [FK_LOTE_CALENDARIO]
GO
ALTER TABLE [G3].[LOTE]  WITH CHECK ADD  CONSTRAINT [FK_LOTE_LINEA] FOREIGN KEY([linea_empaque_id])
REFERENCES [G3].[LINEA_EMPAQUE] ([linea_empaque_id])
GO
ALTER TABLE [G3].[LOTE] CHECK CONSTRAINT [FK_LOTE_LINEA]
GO
ALTER TABLE [G3].[LOTE]  WITH CHECK ADD  CONSTRAINT [FK_LOTE_MERCADO] FOREIGN KEY([mercado_id])
REFERENCES [G3].[MERCADO] ([mercado_id])
GO
ALTER TABLE [G3].[LOTE] CHECK CONSTRAINT [FK_LOTE_MERCADO]
GO
ALTER TABLE [G3].[LOTE]  WITH CHECK ADD  CONSTRAINT [FK_LOTE_PRODUCCION] FOREIGN KEY([produccion_id])
REFERENCES [G3].[PRODUCCION] ([produccion_id])
GO
ALTER TABLE [G3].[LOTE] CHECK CONSTRAINT [FK_LOTE_PRODUCCION]
GO
ALTER TABLE [G3].[LOTE]  WITH CHECK ADD  CONSTRAINT [FK_LOTE_REGION] FOREIGN KEY([region_id])
REFERENCES [G3].[REGION] ([region_id])
GO
ALTER TABLE [G3].[LOTE] CHECK CONSTRAINT [FK_LOTE_REGION]
GO
ALTER TABLE [G3].[METRICA_KILOGRAMO]  WITH CHECK ADD  CONSTRAINT [FK_MK_LOTE] FOREIGN KEY([lote_id])
REFERENCES [G3].[LOTE] ([lote_id])
GO
ALTER TABLE [G3].[METRICA_KILOGRAMO] CHECK CONSTRAINT [FK_MK_LOTE]
GO
ALTER TABLE [G3].[METRICA_KILOGRAMO]  WITH CHECK ADD  CONSTRAINT [FK_MK_METRICA] FOREIGN KEY([metrica_id])
REFERENCES [G3].[METRICA] ([metrica_id])
GO
ALTER TABLE [G3].[METRICA_KILOGRAMO] CHECK CONSTRAINT [FK_MK_METRICA]
GO
ALTER TABLE [G3].[PRODUCCION]  WITH CHECK ADD  CONSTRAINT [FK_PROD_CAMPANA] FOREIGN KEY([campana_id])
REFERENCES [G3].[CAMPANA] ([campana_id])
GO
ALTER TABLE [G3].[PRODUCCION] CHECK CONSTRAINT [FK_PROD_CAMPANA]
GO
ALTER TABLE [G3].[PRODUCCION]  WITH CHECK ADD  CONSTRAINT [FK_PROD_CLIMA_BROTAMIENTO] FOREIGN KEY([fecha_brotamiento])
REFERENCES [G3].[CLIMA] ([fecha])
GO
ALTER TABLE [G3].[PRODUCCION] CHECK CONSTRAINT [FK_PROD_CLIMA_BROTAMIENTO]
GO
ALTER TABLE [G3].[PRODUCCION]  WITH CHECK ADD  CONSTRAINT [FK_PROD_CLIMA_COSECHA] FOREIGN KEY([fecha_cosecha])
REFERENCES [G3].[CLIMA] ([fecha])
GO
ALTER TABLE [G3].[PRODUCCION] CHECK CONSTRAINT [FK_PROD_CLIMA_COSECHA]
GO
ALTER TABLE [G3].[PRODUCCION]  WITH CHECK ADD  CONSTRAINT [FK_PROD_CLIMA_FRUCTIFICACION] FOREIGN KEY([fecha_fructificacion])
REFERENCES [G3].[CLIMA] ([fecha])
GO
ALTER TABLE [G3].[PRODUCCION] CHECK CONSTRAINT [FK_PROD_CLIMA_FRUCTIFICACION]
GO
ALTER TABLE [G3].[PRODUCCION]  WITH CHECK ADD  CONSTRAINT [FK_PROD_CLIMA_PODA] FOREIGN KEY([fecha_poda])
REFERENCES [G3].[CLIMA] ([fecha])
GO
ALTER TABLE [G3].[PRODUCCION] CHECK CONSTRAINT [FK_PROD_CLIMA_PODA]
GO
ALTER TABLE [G3].[PRODUCCION]  WITH CHECK ADD  CONSTRAINT [FK_PROD_VARIEDAD] FOREIGN KEY([variedad_id])
REFERENCES [G3].[VARIEDAD] ([variedad_id])
GO
ALTER TABLE [G3].[PRODUCCION] CHECK CONSTRAINT [FK_PROD_VARIEDAD]
GO
ALTER TABLE [G3].[PRODUCCION_FECHAS]  WITH CHECK ADD  CONSTRAINT [FK_PF_CLIMA] FOREIGN KEY([fecha])
REFERENCES [G3].[CLIMA] ([fecha])
GO
ALTER TABLE [G3].[PRODUCCION_FECHAS] CHECK CONSTRAINT [FK_PF_CLIMA]
GO
ALTER TABLE [G3].[PRODUCCION_FECHAS]  WITH CHECK ADD  CONSTRAINT [FK_PF_PRODUCCION] FOREIGN KEY([produccion_id])
REFERENCES [G3].[PRODUCCION] ([produccion_id])
GO
ALTER TABLE [G3].[PRODUCCION_FECHAS] CHECK CONSTRAINT [FK_PF_PRODUCCION]
GO
ALTER TABLE [G3].[TRABAJADOR_LINEA]  WITH CHECK ADD  CONSTRAINT [FK_TL_LINEA] FOREIGN KEY([linea_empaque_id])
REFERENCES [G3].[LINEA_EMPAQUE] ([linea_empaque_id])
GO
ALTER TABLE [G3].[TRABAJADOR_LINEA] CHECK CONSTRAINT [FK_TL_LINEA]
GO
ALTER TABLE [G3].[TRABAJADOR_LINEA]  WITH CHECK ADD  CONSTRAINT [FK_TL_TRABAJADOR] FOREIGN KEY([trabajador_id])
REFERENCES [G3].[TRABAJADOR] ([trabajador_id])
GO
ALTER TABLE [G3].[TRABAJADOR_LINEA] CHECK CONSTRAINT [FK_TL_TRABAJADOR]
GO
